mod common;
use axiom::IntentContext;
use std::fs;

#[test]
fn test_git_status_insight() {
    let mut session = common::setup_session();
    let command = "git status";
    let context = IntentContext {
        last_message: "check git status".to_string(),
        command: command.to_string(),
        keywords: vec![],
    };

    let raw_output = fs::read_to_string("tests/fixtures/git_status_raw.txt")
        .expect("Failed to load git status fixture");

    for line in raw_output.lines() {
        session.engine.process_line(line, command, &context);
    }

    let summaries = session.engine.flush_summaries();
    
    let mut found_insight = false;
    for summary in summaries {
        if summary.contains("Semantic Insight: Repository has pending changes") {
            found_insight = true;
            assert!(summary.contains("1 modified"));
            assert!(summary.contains("1 untracked"));
        }
    }
    
    assert!(found_insight, "Git status insight should be generated by GitHandler");
}

#[test]
fn test_git_log_insight() {
    let mut session = common::setup_session();
    let command = "git log --oneline";
    let context = IntentContext {
        last_message: "show history".to_string(),
        command: command.to_string(),
        keywords: vec![],
    };

    let raw_output = fs::read_to_string("tests/fixtures/git_log_raw.txt")
        .expect("Failed to load git log fixture");

    for line in raw_output.lines() {
        session.engine.process_line(line, command, &context);
    }

    let summaries = session.engine.flush_summaries();
    
    let mut found_insight = false;
    for summary in summaries {
        if summary.contains("Semantic Insight: Detected active history") {
            found_insight = true;
            assert!(summary.contains("3 commits"));
        }
    }
    
    assert!(found_insight, "Git log insight should be generated by GitHandler");
}
