name: git-status
command_pattern: "^git status.*"
rules:
  - name: Boilerplate
    pattern: "^(Changes|Untracked|nothing|no changes|\\s*\\(use).*"
    action: hidden
    priority: 25
  - name: SectionHeaders
    pattern: "^.* files:.*"
    action: hidden
    priority: 25
  - name: StatusHeader
    pattern: "^On branch.*"
    action: keep
    priority: 20
  - name: ModifiedFiles
    pattern: "^\\s*modified:.*"
    action: synthesize
    priority: 10
  - name: NewFiles
    pattern: "^\\s*new file:.*"
    action: synthesize
    priority: 10
  - name: UntrackedFiles
    pattern: "^\\s+[^\\s(].*"
    action: synthesize
    priority: 5
