name: linux-ls
command_pattern: "^ls"
rules:
  - name: HiddenFiles
    pattern: "^\\..*"
    action: collapse
    priority: 1
  - name: NodeModules
    pattern: ".*node_modules.*"
    action: collapse
    priority: 10
  - name: CommonMetadata
    pattern: "^(total [0-9]+)"
    action: collapse
    priority: 5
  - name: LongPerms
    pattern: "^[-dclpsb][rwx-]{9}.*"
    action: collapse
    priority: 3
