name: linux-ps
command_pattern: "^ps"
rules:
  - name: Header
    pattern: "^(USER|PID|%CPU).*"
    action: keep
    priority: 10
  - name: KernelTasks
    pattern: ".*\\[[a-zA-Z0-9/-]+\\].*"
    action: collapse
    priority: 5
  - name: SystemdTasks
    pattern: ".*/lib/systemd/.*"
    action: collapse
    priority: 5
  - name: BrowserNoise
    pattern: ".*(--type=renderer|--type=gpu-process|--type=utility).*"
    action: collapse
    priority: 3
  - name: IdleProcs
    pattern: ".*\\s+0:00\\s+.*"
    action: collapse
    priority: 1
